[package]
name = "hellinger-estimates"
version = "1.0.0"
description = "Tests for Hellinger distance between an analytical CDF and an empirical sample"
edition = "2024"
documentation = "https://docs.rs/hellinger-estimates"
categories = ["statistics"]
rust-version = "1.88"

authors = ["Aurelia Molzer <5550310+197g@users.noreply.github.com>"]
license = "EUPL-1.1+"
repository = "https://github.com/197g/bhattacharyya-estimator"
readme = "Readme.md"

[dependencies.statrs]
version = "0.19"
optional = true
default-features = false

[features]
default = ["statrs"]
statrs = ["dep:statrs"]

[dev-dependencies]
rand = "0.10"
statrs = { version = "*", default-features = false, features = ["rand"] }

ndarray = "0.16"
nalgebra = "0.34"
nalgebra-sparse = "0.11"
# WTF both nalgebra and ndarray. Stupid LLM. Please point me to a better PCA
# implementation that still has a partial top-n-component method?
single_algebra = "0.9"
linfa-datasets = { version = "0.8", features = ["diabetes", "winequality"] }

[profile.test-performant]
inherits = "release"
debug-assertions = true

[[test]]
name = "distribution-std"
path = "tests/distribution-std.rs"
required-features = ["statrs"]
